version: "3.8"

services:
  osrm_postgres:
    image: postgres:latest
    container_name: osrm_postgres
    environment:
      POSTGRES_USER: osrm_user
      POSTGRES_PASSWORD: Pas3w0rd
      POSTGRES_DB: osrm_routes
    networks:
      - osrm_network
    ports:
      - "5444:5432"
    command: ["postgres", "-c", "password_encryption=md5"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  osrm:
    build: 
      context: .
      dockerfile: images/osrm/Dockerfile
    container_name: osrm_routing
    environment:
      - POSTGRES_HOST=osrm_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=osrm_user
      - POSTGRES_PASSWORD=Pas3w0rd
      - POSTGRES_DB=osrm_routes
    depends_on:
      - osrm_postgres
    networks:
      - osrm_network
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
      - ./profiles/inclusive_profile.lua:/inclusive_profile.lua
      - ./hooks:/hooks
    command: >
      bash -c "
        python3 /hooks/generate_custom_weights.py &&
        osrm-extract -p /inclusive_profile.lua /data/map.osm.pbf &&
        osrm-contract /data/map.osrm &&
        osrm-routed /data/map.osrm
      "

networks:
  osrm_network:
    driver: bridge

volumes:
  pgdata:
